name: Create Scratch Org and retrieve Metadata

on:
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          yarn global add sfdx-cli
      - name: Retrieve from Scratch Org
        env:
          SFDX_AUTH_URL_DEVHUB: ${{ secrets.SFDX_AUTH_URL_DEVHUB }}
        run: |
          sfdx auth:sfdxurl:store -d -a devhub -f /dev/stdin <<< "${SFDX_AUTH_URL_DEVHUB}"
          sfdx force:org:create -f config/project-scratch-def.json -a scratch-org-shape -s
          rm -rf force-app/main
          sfdx force:source:manifest:create --fromorg scratch-org-shape
          sfdx force:source:retrieve -x package.xml
      - name: Create Pull Request
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: force-app
          commit_message: "feat: retrieve Metadata from Scratch Org"
      - name: Delete scratch org
        if: always()
        run: |
          sfdx force:org:delete -p
