name: Create Scratch Org and retrieve Metadata

on:
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install --global @salesforce/cli
      - name: Retrieve from Scratch Org
        env:
          SFDX_AUTH_URL_DEVHUB: ${{ secrets.SFDX_AUTH_URL_DEVHUB }}
        run: |
          echo "${SFDX_AUTH_URL_DEVHUB}" | sf org login sfdx-url --set-default-dev-hub --alias devhub --sfdx-url-stdin
          sf org create scratch -f config/project-scratch-def.json --alias scratch-org-shape --set-default
          rm -rf force-app/main
          sf project generate manifest --from-org scratch-org-shape
          sf project retrieve start --manifest package.xml
      - name: Create Pull Request
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: force-app
          commit_message: "feat: retrieve Metadata from Scratch Org"
      - name: Delete scratch org
        if: always()
        run: |
          sf org delete scratch -p
