name: Create Scratch Org and retrieve Metadata settings

on:
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Authenticate DevHub and create scratch org
        env:
          SFDX_AUTH_URL_DEVHUB: ${{ secrets.SFDX_AUTH_URL_DEVHUB }}
        run: |
          npx sfdx auth:sfdxurl:store -d -a devhub -f /dev/stdin < <(echo "${SFDX_AUTH_URL_DEVHUB}")
          npx sfdx force:org:create -f config/project-scratch-def.json -a scratch-org-shape -s
          npx sfdx force:source:retrieve -m Settings
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: |
            force-app
          commit-message: "feat: export settings from Scratch Org"
          title: "feat: export settings from Scratch Org"
          branch: ${{ github.ref_name }}
      - name: Delete scratch org
        if: always()
        run: |
          npx sfdx force:org:delete -p
